"use client";

import { useActionState } from "react";

import { Button, Checkbox, FileUpload, Input, Select } from "@/components";
import type { ProductFormState } from "./form-state";

function Message({ state }: { state: ProductFormState }) { return state.message ? <p className={`text-sm ${state.status === "success" ? "text-palm" : "text-red-800"}`} role="status">{state.message}</p> : null; }
export function StockForm({ action, quantity }: { action: (state: ProductFormState, data: FormData) => Promise<ProductFormState>; quantity: number }) { const [state, formAction, pending] = useActionState(action, { status: "idle" } satisfies ProductFormState); return <form action={formAction} className="space-y-4"><Input defaultValue={quantity} error={state.fieldErrors?.stockQuantity?.[0]} label="Available stock" min={0} name="stockQuantity" required type="number"/><Message state={state}/><Button disabled={pending} type="submit">Update stock</Button></form>; }
export function VariantForm({ action }: { action: (state: ProductFormState, data: FormData) => Promise<ProductFormState> }) { const [state, formAction, pending] = useActionState(action, { status: "idle" } satisfies ProductFormState); return <form action={formAction} className="grid gap-4 sm:grid-cols-2"><Input error={state.fieldErrors?.name?.[0]} label="Variant name" name="name" required/><Select label="Option type" name="optionType"><option value="size">Size</option><option value="weight">Weight</option><option value="pack_size">Pack size</option><option value="breed">Breed</option><option value="age">Age</option><option value="sex">Sex</option><option value="presentation">Presentation</option></Select><Input label="Option value" name="optionValue" required/><Input label="SKU" name="sku"/><Input error={state.fieldErrors?.priceKobo?.[0]} label="Price (₦)" min="0.01" name="priceKobo" required step="0.01" type="number"/><Input label="Stock" min={0} name="stockQuantity" required type="number"/><Checkbox defaultChecked label="Variant is active" name="isActive"/><div className="sm:col-span-2"><Message state={state}/><Button className="mt-3" disabled={pending} type="submit">Add variant</Button></div></form>; }
export function BulkTierForm({ action }: { action: (state: ProductFormState, data: FormData) => Promise<ProductFormState> }) { const [state, formAction, pending] = useActionState(action, { status: "idle" } satisfies ProductFormState); return <form action={formAction} className="grid gap-4 sm:grid-cols-3"><Input label="Minimum quantity" min={1} name="minimumQuantity" required type="number"/><Input hint="Leave empty for no upper limit." label="Maximum quantity" min={1} name="maximumQuantity" type="number"/><Input error={state.fieldErrors?.unitPriceKobo?.[0]} label="Unit price (₦)" min="0.01" name="unitPriceKobo" required step="0.01" type="number"/><div className="sm:col-span-3"><Message state={state}/><Button className="mt-3" disabled={pending} type="submit">Add price tier</Button></div></form>; }
export function ProductImageForm({ action }: { action: (state: ProductFormState, data: FormData) => Promise<ProductFormState> }) { const [state, formAction, pending] = useActionState(action, { status: "idle" } satisfies ProductFormState); return <form action={formAction} className="space-y-4" encType="multipart/form-data"><FileUpload accept="image/png,image/jpeg,image/webp" hint="PNG, JPEG or WebP, up to 8 MB. Images are optimized to WebP." label="Product image" name="image" required/><Input label="Alternative text" name="altText"/><Message state={state}/><Button disabled={pending} type="submit">{pending ? "Optimizing…" : "Upload image"}</Button></form>; }
