import { notFound } from "next/navigation";
import { Button, Card, StatusBadge } from "@/components";
import { requireApprovedSeller } from "@/server/authorization";
import { getActiveProductCategories, getProductForSeller, ProductAccessError } from "@/server/services/product-catalogue";
import { publishProductAction, submitProductAction, updateProductAction } from "../../actions";
import { ProductForm } from "../../product-form";
import { ProductNav } from "../../product-nav";
const tones = { DRAFT: "draft", PENDING_REVIEW: "pending", APPROVED: "success", REJECTED: "error", SUSPENDED: "suspended", ARCHIVED: "draft" } as const;
export default async function EditProductPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string }> }) { const [{ id }, query, user] = await Promise.all([params, searchParams, requireApprovedSeller()]); let product; try { product = await getProductForSeller(id, user.id); } catch (error) { if (error instanceof ProductAccessError) notFound(); throw error; } const categories = await getActiveProductCategories(); return <section><ProductNav id={id}/><div className="flex flex-wrap items-center gap-3"><h1 className="font-display text-4xl font-black text-coop">{product.name}</h1><StatusBadge status={tones[product.status]}/></div>{query.created ? <p className="mt-4 rounded-control bg-palm/10 px-4 py-3 text-sm text-palm">Draft created. Add images and selling options before submission.</p> : null}{product.rejectionReason ? <p className="mt-4 rounded-control bg-red-50 px-4 py-3 text-sm text-red-800"><strong>Review feedback:</strong> {product.rejectionReason}</p> : null}<div className="mt-6 grid gap-6 xl:grid-cols-[1fr_18rem]"><Card className="p-5 sm:p-7"><ProductForm action={updateProductAction.bind(null, id)} categories={categories} label="Save product" values={product}/></Card><Card className="h-fit p-5"><h2 className="font-display text-xl font-bold text-coop">Availability</h2><p className="mt-2 text-sm leading-6 text-coop/60">Material edits to an approved listing return it to review.</p>{["DRAFT", "REJECTED"].includes(product.status) ? <form action={submitProductAction.bind(null, id)} className="mt-4"><Button className="w-full" type="submit">Submit for review</Button></form> : null}{product.status === "APPROVED" ? <form action={publishProductAction.bind(null, id, !product.isPublished)} className="mt-4"><Button className="w-full" type="submit" variant={product.isPublished ? "outline" : "primary"}>{product.isPublished ? "Unpublish" : "Publish product"}</Button></form> : null}<p className="mt-4 text-xs text-coop/50">{product.isPublished ? "Visible to marketplace buyers" : "Not publicly listed"}</p></Card></div></section>; }
