CREATE TABLE `Product` (
 `id` VARCHAR(191) NOT NULL, `sellerId` VARCHAR(191) NOT NULL, `categoryId` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `slug` VARCHAR(191) NOT NULL,
 `shortDescription` VARCHAR(191) NULL, `description` TEXT NOT NULL, `brand` VARCHAR(191) NULL, `species` VARCHAR(191) NULL, `condition` VARCHAR(191) NULL, `sku` VARCHAR(191) NULL,
 `basePriceKobo` INTEGER NOT NULL, `stockQuantity` INTEGER NOT NULL DEFAULT 0, `minimumOrderQuantity` INTEGER NOT NULL DEFAULT 1, `unitLabel` VARCHAR(191) NOT NULL DEFAULT 'item',
 `status` ENUM('DRAFT','PENDING_REVIEW','APPROVED','REJECTED','SUSPENDED','ARCHIVED') NOT NULL DEFAULT 'DRAFT', `isFeatured` BOOLEAN NOT NULL DEFAULT false, `isPublished` BOOLEAN NOT NULL DEFAULT false,
 `manufacturer` VARCHAR(191) NULL, `activeIngredient` VARCHAR(191) NULL, `dosageForm` VARCHAR(191) NULL, `packSize` VARCHAR(191) NULL, `expiryDate` DATETIME(3) NULL,
 `rejectionReason` TEXT NULL, `moderatedAt` DATETIME(3) NULL, `moderatedByUserId` VARCHAR(191) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
 UNIQUE INDEX `Product_sellerId_slug_key`(`sellerId`,`slug`), UNIQUE INDEX `Product_sellerId_sku_key`(`sellerId`,`sku`), INDEX `Product_categoryId_status_isPublished_idx`(`categoryId`,`status`,`isPublished`),
 INDEX `Product_sellerId_status_updatedAt_idx`(`sellerId`,`status`,`updatedAt`), INDEX `Product_moderatedByUserId_idx`(`moderatedByUserId`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ProductVariant` (`id` VARCHAR(191) NOT NULL, `productId` VARCHAR(191) NOT NULL, `name` VARCHAR(191) NOT NULL, `options` JSON NOT NULL, `sku` VARCHAR(191) NULL, `priceKobo` INTEGER NOT NULL, `stockQuantity` INTEGER NOT NULL DEFAULT 0, `isActive` BOOLEAN NOT NULL DEFAULT true, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `ProductVariant_productId_sku_key`(`productId`,`sku`), INDEX `ProductVariant_productId_isActive_idx`(`productId`,`isActive`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `ProductImage` (`id` VARCHAR(191) NOT NULL, `productId` VARCHAR(191) NOT NULL, `path` VARCHAR(191) NOT NULL, `altText` VARCHAR(191) NULL, `sortOrder` INTEGER NOT NULL DEFAULT 0, `isPrimary` BOOLEAN NOT NULL DEFAULT false, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, INDEX `ProductImage_productId_sortOrder_idx`(`productId`,`sortOrder`), INDEX `ProductImage_productId_isPrimary_idx`(`productId`,`isPrimary`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `BulkPriceTier` (`id` VARCHAR(191) NOT NULL, `productId` VARCHAR(191) NOT NULL, `minimumQuantity` INTEGER NOT NULL, `maximumQuantity` INTEGER NULL, `unitPriceKobo` INTEGER NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `BulkPriceTier_productId_minimumQuantity_key`(`productId`,`minimumQuantity`), INDEX `BulkPriceTier_productId_minimumQuantity_idx`(`productId`,`minimumQuantity`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Product` ADD CONSTRAINT `Product_sellerId_fkey` FOREIGN KEY (`sellerId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Product` ADD CONSTRAINT `Product_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `Category`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `Product` ADD CONSTRAINT `Product_moderatedByUserId_fkey` FOREIGN KEY (`moderatedByUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `ProductVariant` ADD CONSTRAINT `ProductVariant_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ProductImage` ADD CONSTRAINT `ProductImage_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `BulkPriceTier` ADD CONSTRAINT `BulkPriceTier_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
