import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Badge, Breadcrumb, Card, Money, ProductGallery, ProductListingCard, PurchasePanel } from "@/components";
import { getMarketplaceProductBySlug, getRelatedMarketplaceProducts } from "@/server/services/marketplace-search";

type Props = { params: Promise<{ productSlug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const product = await getMarketplaceProductBySlug((await params).productSlug);
  if (!product) return { title: "Product not found" };
  const description = product.shortDescription || product.description.slice(0, 155);
  const image = product.images[0]?.path || product.category.imagePath || undefined;
  return { title: product.name, description, alternates: { canonical: `/marketplace/${product.slug}` }, openGraph: { title: product.name, description, type: "website", images: image ? [{ url: image, alt: product.name }] : undefined } };
}

export default async function MarketplaceProductPage({ params }: Props) {
  const product = await getMarketplaceProductBySlug((await params).productSlug);
  if (!product) notFound();
  const related = await getRelatedMarketplaceProducts(product.id, product.categoryId);
  const parent = product.category.parent;
  const categoryHref = parent ? `/marketplace/category/${parent.slug}/${product.category.slug}` : `/marketplace/category/${product.category.slug}`;
  const fallback = product.category.imagePath || parent?.imagePath || "/images/poultry/live-birds.webp";
  const veterinary = [["Manufacturer", product.manufacturer], ["Active ingredient", product.activeIngredient], ["Dosage form", product.dosageForm], ["Pack size", product.packSize], ["Expiry date", product.expiryDate?.toLocaleDateString("en-NG", { dateStyle: "medium" })]].filter((item): item is [string, string] => Boolean(item[1]));
  const details = [["Species", product.species], ["Condition", product.condition], ["Brand", product.brand], ["Presentation", product.packSize], ["Minimum order", `${product.minimumOrderQuantity} ${product.unitLabel}${product.minimumOrderQuantity === 1 ? "" : "s"}`]].filter((item): item is [string, string] => Boolean(item[1]));
  const structuredData = { "@context": "https://schema.org", "@type": "Product", name: product.name, description: product.shortDescription || product.description, image: product.images.map((image) => image.path), sku: product.sku || undefined, brand: product.brand ? { "@type": "Brand", name: product.brand } : undefined, offers: { "@type": "Offer", priceCurrency: "NGN", price: (product.basePriceKobo / 100).toFixed(2), availability: product.stockQuantity > 0 || product.variants.some((variant) => variant.stockQuantity > 0) ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", url: `/marketplace/${product.slug}`, seller: { "@type": "Organization", name: product.seller.sellerProfile?.businessName || product.seller.username } } };
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-6 lg:px-8 lg:py-12"><script dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} type="application/ld+json"/><Breadcrumb items={[{ label: "Marketplace", href: "/marketplace" }, ...(parent ? [{ label: parent.name, href: `/marketplace/category/${parent.slug}` }] : []), { label: product.category.name, href: categoryHref }, { label: product.name }]}/><div className="mt-7 grid gap-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(22rem,.95fr)]"><ProductGallery fallback={fallback} images={product.images} productName={product.name}/><div><div className="flex flex-wrap gap-2"><Badge tone="palm">Approved listing</Badge>{product.isFeatured ? <Badge tone="yolk">Featured</Badge> : null}{product.bulkPriceTiers.length ? <Badge tone="sack">Bulk pricing</Badge> : null}</div><h1 className="mt-4 font-display text-4xl font-black leading-tight text-coop sm:text-5xl">{product.name}</h1>{product.shortDescription ? <p className="mt-3 text-lg leading-7 text-coop/65">{product.shortDescription}</p> : null}<Link className="mt-5 flex items-center gap-3 rounded-card border border-coop/10 bg-white p-4 hover:border-palm/30" href={`/marketplace/sellers/${product.seller.username}`}><span className="grid size-11 place-items-center rounded-full bg-yolk font-display text-lg font-black text-coop">{product.seller.sellerProfile?.businessName?.charAt(0) || "S"}</span><span><span className="block text-xs font-bold uppercase tracking-market text-coop/45">Sold by</span><span className="font-bold text-palm">{product.seller.sellerProfile?.businessName || product.seller.username}</span>{product.seller.sellerProfile?.state ? <span className="ml-2 text-sm text-coop/50">· {product.seller.sellerProfile.state}</span> : null}</span></Link><div className="mt-6"><PurchasePanel basePriceKobo={product.basePriceKobo} minimumOrderQuantity={product.minimumOrderQuantity} stockQuantity={product.stockQuantity} unitLabel={product.unitLabel} variants={product.variants}/></div></div></div>
    <div className="mt-12 grid gap-8 lg:grid-cols-[minmax(0,1fr)_20rem]"><div className="space-y-8"><section><h2 className="font-display text-2xl font-black text-coop">Product details</h2><p className="mt-4 whitespace-pre-wrap leading-7 text-coop/70">{product.description}</p>{details.length ? <dl className="mt-6 grid gap-3 sm:grid-cols-2">{details.map(([label, value]) => <Card className="p-4" key={label}><dt className="text-xs font-bold uppercase tracking-market text-coop/45">{label}</dt><dd className="mt-1 font-semibold text-coop">{value}</dd></Card>)}</dl> : null}</section>{product.bulkPriceTiers.length ? <section><h2 className="font-display text-2xl font-black text-coop">Bulk pricing</h2><div className="mt-4 overflow-hidden rounded-card border border-coop/10 bg-white">{product.bulkPriceTiers.map((tier) => <div className="flex items-center justify-between border-b border-coop/8 px-4 py-3 last:border-0" key={tier.id}><span className="text-sm text-coop/65">{tier.minimumQuantity}{tier.maximumQuantity ? `–${tier.maximumQuantity}` : "+"} {product.unitLabel}s</span><span><Money amount={tier.unitPriceKobo / 100} className="text-palm"/> <span className="text-xs text-coop/45">each</span></span></div>)}</div></section> : null}{veterinary.length ? <section className="rounded-panel border border-palm/15 bg-palm/5 p-6"><p className="market-label text-palm">Veterinary information</p><h2 className="mt-2 font-display text-2xl font-black text-coop">Use responsibly</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2">{veterinary.map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-market text-coop/45">{label}</dt><dd className="mt-1 text-sm font-semibold text-coop">{value}</dd></div>)}</dl><p className="mt-5 text-xs leading-5 text-coop/55">Follow the product label and seek qualified veterinary guidance where appropriate.</p></section> : null}</div><aside><Card className="p-5"><p className="market-label text-sack">Delivery · Phase 3</p><h2 className="mt-2 font-display text-xl font-bold text-coop">Delivery options are coming</h2><p className="mt-3 text-sm leading-6 text-coop/60">Location-based delivery quotes, pickup terms and live-bird handling guidance will appear here when checkout launches.</p></Card></aside></div>
    {related.length ? <section className="mt-14 border-t border-coop/10 pt-10"><p className="market-label text-sack">More in {product.category.name}</p><h2 className="mt-2 font-display text-3xl font-black text-coop">Related products</h2><div className="mt-6 grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-4">{related.map((item) => <ProductListingCard key={item.id} product={item}/>)}</div></section> : null}
  </div>;
}
