import type { Metadata } from "next";
import Link from "next/link";

import { EmptyState, MarketplaceCategoryStrip, MarketplaceFilters, Pagination, ProductListingCard, ResponsiveImage, ResultsToolbar, buttonStyles } from "@/components";
import { getPublicCategories } from "@/server/categories";
import { getFeaturedMarketplaceProducts, getFeaturedSellers, getMarketplaceFacets, getRecentMarketplaceProducts, searchMarketplace } from "@/server/services/marketplace-search";
import { filterFormValues, marketplacePageHref, parseMarketplaceParams, type PublicSearchParams } from "@/server/validation/marketplace";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Poultry marketplace", description: "Shop live birds, chicks, eggs, feed, poultry equipment and farm supplies from approved sellers." };

export default async function MarketplacePage({ searchParams }: { searchParams: Promise<PublicSearchParams> }) {
  const raw = await searchParams;
  const filters = parseMarketplaceParams(raw);
  const browsing = Boolean(filters.q || filters.category || filters.subcategory || filters.species || filters.condition || filters.seller || filters.inStock || filters.attributeValue || filters.minPriceKobo !== undefined || filters.maxPriceKobo !== undefined);
  const [categories, facets, results, discovery] = await Promise.all([getPublicCategories(), getMarketplaceFacets(), searchMarketplace(filters), browsing ? Promise.resolve([[], [], []] as const) : Promise.all([getFeaturedMarketplaceProducts(), getRecentMarketplaceProducts(), getFeaturedSellers()])]);
  const [featured, recent, sellers] = discovery;
  return <div>
    <section className="relative isolate overflow-hidden bg-coop text-white"><ResponsiveImage alt="Poultry farmers tending market-ready birds" className="-z-20 opacity-55" fill priority src="/images/poultry/marketplace-hero.webp"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-coop via-coop/85 to-coop/25"/><div className="mx-auto max-w-7xl px-5 py-12 sm:px-6 lg:px-8 lg:py-20"><p className="market-label text-yolk">The practical poultry market</p><h1 className="mt-3 max-w-3xl font-display text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">Everything your flock and farm need, in one place.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/75 sm:text-lg">Find approved poultry sellers, compare farm-gate listings and buy across the complete poultry value chain.</p><form action="/marketplace" className="relative mt-7 max-w-3xl" role="search"><label className="sr-only" htmlFor="marketplace-search">Search marketplace</label><input className="h-14 w-full rounded-card border-2 border-white/20 bg-white pl-12 pr-28 text-base text-coop outline-none placeholder:text-coop/45 focus:border-yolk" defaultValue={filters.q} id="marketplace-search" name="q" placeholder="Search birds, feed, eggs, incubators…"/><svg aria-hidden="true" className="absolute left-4 top-[1.15rem] size-5 text-coop/45" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><button className="absolute bottom-1.5 right-1.5 top-1.5 rounded-control bg-yolk px-5 text-sm font-black text-coop hover:bg-white" type="submit">Search</button></form><div className="mt-5 flex flex-wrap gap-2">{["Live birds", "Day-old chicks", "Layer mash", "Incubators"].map((term) => <Link className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold text-white backdrop-blur hover:bg-white hover:text-coop" href={`/marketplace?q=${encodeURIComponent(term)}`} key={term}>{term}</Link>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="market-label text-sack">Shop by value chain</p><h2 className="mt-2 font-display text-3xl font-black text-coop">Top poultry categories</h2></div><Link className="hidden text-sm font-bold text-palm sm:block" href="/categories">View all categories →</Link></div><div className="mt-6"><MarketplaceCategoryStrip categories={categories}/></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{categories.flatMap((category) => category.children.slice(0, 2).map((child) => <Link className="whitespace-nowrap rounded-full border border-coop/15 bg-white px-4 py-2 text-sm font-semibold text-coop hover:border-palm hover:text-palm" href={`/marketplace/category/${category.slug}/${child.slug}`} key={child.id}>{child.name}</Link>))}</div></section>
    {!browsing ? <><section className="border-y border-coop/8 bg-white/55"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:px-8"><p className="market-label text-sack">Selected for buyers</p><h2 className="mt-2 font-display text-3xl font-black text-coop">Featured products</h2>{featured.length ? <div className="mt-6 grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-4">{featured.map((product) => <ProductListingCard key={product.id} product={product}/>)}</div> : <div className="mt-6"><EmptyState description="Featured approved listings will appear here as the marketplace catalogue grows." title="Featured shelf coming soon"/></div>}</div></section><section className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:px-8"><p className="market-label text-sack">Fresh from approved sellers</p><h2 className="mt-2 font-display text-3xl font-black text-coop">Recently added</h2>{recent.length ? <div className="mt-6 grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-4">{recent.map((product) => <ProductListingCard key={product.id} product={product}/>)}</div> : <div className="mt-6"><EmptyState description="Newly approved seller products will be placed here automatically." title="The first listings are on their way"/></div>}</section>{sellers.length ? <section className="bg-coop text-white"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-6 lg:px-8"><p className="market-label text-yolk">Trusted storefronts</p><h2 className="mt-2 font-display text-3xl font-black">Featured sellers</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{sellers.map((seller) => <Link className="rounded-card border border-white/10 bg-white/5 p-5 transition hover:bg-white/10" href={`/marketplace/sellers/${seller.username}`} key={seller.username}><div className="flex items-center gap-3"><div className="relative size-12 overflow-hidden rounded-full bg-yolk text-coop">{seller.sellerProfile?.logoPath ? <ResponsiveImage alt="" fill src={seller.sellerProfile.logoPath}/> : <span className="grid h-full place-items-center font-display text-xl font-black">{seller.sellerProfile?.businessName?.charAt(0) || "S"}</span>}</div><div><h3 className="font-display text-lg font-bold">{seller.sellerProfile?.businessName || seller.username}</h3><p className="text-xs text-white/60">{seller._count.products} public products</p></div></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-white/65">{seller.sellerProfile?.description || "Approved poultry marketplace seller."}</p></Link>)}</div></div></section> : null}</> : null}
    <section className="mx-auto max-w-7xl px-5 py-12 sm:px-6 lg:px-8"><div className="mb-7"><p className="market-label text-sack">Marketplace catalogue</p><h2 className="mt-2 font-display text-3xl font-black text-coop">{filters.q ? `Results for “${filters.q}”` : "Browse all products"}</h2></div><div className="grid gap-6 lg:grid-cols-[17rem_minmax(0,1fr)]"><MarketplaceFilters categories={categories} facets={facets} values={filterFormValues(raw)}/><div><ResultsToolbar action="/marketplace" params={raw} total={results.total}/>{results.products.length ? <div className="mt-6 grid grid-cols-2 gap-3 sm:gap-5 xl:grid-cols-3">{results.products.map((product) => <ProductListingCard key={product.id} product={product}/>)}</div> : <div className="mt-6"><EmptyState action={<Link className={buttonStyles()} href="/marketplace">Clear filters</Link>} description="Try a broader term, another category or remove one of your filters." icon="search" title="No products matched"/></div>}{results.totalPages > 1 ? <div className="mt-9"><Pagination currentPage={results.page} getHref={(page) => marketplacePageHref("/marketplace", raw, page)} totalPages={results.totalPages}/></div> : null}</div></div></section>
  </div>;
}
